package op5

type HostQueries []struct {
	AcceptPassiveChecks               int             `json:"accept_passive_checks"`
	Acknowledged                      int             `json:"acknowledged"`
	AcknowledgementType               int             `json:"acknowledgement_type"`
	ActionURL                         string          `json:"action_url"`
	ActiveChecksEnabled               int             `json:"active_checks_enabled"`
	Address                           string          `json:"address"`
	Alias                             string          `json:"alias"`
	CheckCommand                      string          `json:"check_command"`
	CheckFlappingRecoveryNotification int             `json:"check_flapping_recovery_notification"`
	CheckFreshness                    int             `json:"check_freshness"`
	CheckInterval                     int             `json:"check_interval"`
	CheckOptions                      int             `json:"check_options"`
	CheckPeriod                       string          `json:"check_period"`
	CheckSource                       string          `json:"check_source"`
	CheckType                         int             `json:"check_type"`
	ChecksEnabled                     int             `json:"checks_enabled"`
	Childs                            []interface{}   `json:"childs"`
	Comments                          []interface{}   `json:"comments"`
	CommentsWithInfo                  []interface{}   `json:"comments_with_info"`
	ContactGroups                     []interface{}   `json:"contact_groups"`
	Contacts                          []string        `json:"contacts"`
	CurrentAttempt                    int             `json:"current_attempt"`
	CurrentNotificationNumber         int             `json:"current_notification_number"`
	CustomVariableNames               []interface{}   `json:"custom_variable_names"`
	CustomVariableValues              []interface{}   `json:"custom_variable_values"`
	CustomVariables                   []interface{}   `json:"custom_variables"`
	DisplayName                       string          `json:"display_name"`
	Downtimes                         []interface{}   `json:"downtimes"`
	DowntimesWithInfo                 []interface{}   `json:"downtimes_with_info"`
	EventHandler                      string          `json:"event_handler"`
	EventHandlerEnabled               int             `json:"event_handler_enabled"`
	ExecutionTime                     float64         `json:"execution_time"`
	Filename                          string          `json:"filename"`
	FirstNotificationDelay            int             `json:"first_notification_delay"`
	FlapDetectionEnabled              int             `json:"flap_detection_enabled"`
	Groups                            []interface{}   `json:"groups"`
	HardState                         int             `json:"hard_state"`
	HasBeenChecked                    int             `json:"has_been_checked"`
	HighFlapThreshold                 int             `json:"high_flap_threshold"`
	HourlyValue                       int             `json:"hourly_value"`
	IconImage                         string          `json:"icon_image"`
	IconImageAlt                      string          `json:"icon_image_alt"`
	InCheckPeriod                     int             `json:"in_check_period"`
	InNotificationPeriod              int             `json:"in_notification_period"`
	InitialState                      int             `json:"initial_state"`
	IsExecuting                       int             `json:"is_executing"`
	IsFlapping                        int             `json:"is_flapping"`
	LastCheck                         int             `json:"last_check"`
	LastHardState                     int             `json:"last_hard_state"`
	LastHardStateChange               int             `json:"last_hard_state_change"`
	LastNotification                  int             `json:"last_notification"`
	LastState                         int             `json:"last_state"`
	LastStateChange                   int             `json:"last_state_change"`
	LastTimeDown                      int             `json:"last_time_down"`
	LastTimeUnreachable               int             `json:"last_time_unreachable"`
	LastTimeUp                        int             `json:"last_time_up"`
	Latency                           float64         `json:"latency"`
	LongPluginOutput                  string          `json:"long_plugin_output"`
	LowFlapThreshold                  int             `json:"low_flap_threshold"`
	MaxCheckAttempts                  int             `json:"max_check_attempts"`
	ModifiedAttributes                int             `json:"modified_attributes"`
	ModifiedAttributesList            []interface{}   `json:"modified_attributes_list"`
	Name                              string          `json:"name"`
	NextCheck                         int             `json:"next_check"`
	NextNotification                  int             `json:"next_notification"`
	NoMoreNotifications               int             `json:"no_more_notifications"`
	Notes                             string          `json:"notes"`
	NotesURL                          string          `json:"notes_url"`
	NotificationInterval              int             `json:"notification_interval"`
	NotificationPeriod                string          `json:"notification_period"`
	NotificationsEnabled              int             `json:"notifications_enabled"`
	NumServices                       int             `json:"num_services"`
	NumServicesCrit                   int             `json:"num_services_crit"`
	NumServicesHardCrit               int             `json:"num_services_hard_crit"`
	NumServicesHardOk                 int             `json:"num_services_hard_ok"`
	NumServicesHardUnknown            int             `json:"num_services_hard_unknown"`
	NumServicesHardWarn               int             `json:"num_services_hard_warn"`
	NumServicesOk                     int             `json:"num_services_ok"`
	NumServicesPending                int             `json:"num_services_pending"`
	NumServicesUnknown                int             `json:"num_services_unknown"`
	NumServicesWarn                   int             `json:"num_services_warn"`
	Obsess                            int             `json:"obsess"`
	Parents                           []interface{}   `json:"parents"`
	PendingFlexDowntime               int             `json:"pending_flex_downtime"`
	PercentStateChange                int             `json:"percent_state_change"`
	PerfDataRaw                       string          `json:"perf_data_raw"`
	PluginOutput                      string          `json:"plugin_output"`
	PnpgraphPresent                   int             `json:"pnpgraph_present"`
	ProcessPerformanceData            int             `json:"process_performance_data"`
	RetryInterval                     int             `json:"retry_interval"`
	ScheduledDowntimeDepth            int             `json:"scheduled_downtime_depth"`
	Services                          []string        `json:"services"`
	ServicesWithInfo                  [][]interface{} `json:"services_with_info"`
	ServicesWithState                 [][]interface{} `json:"services_with_state"`
	ShouldBeScheduled                 int             `json:"should_be_scheduled"`
	State                             int             `json:"state"`
	StateType                         int             `json:"state_type"`
	StatusmapImage                    string          `json:"statusmap_image"`
	TotalServices                     int             `json:"total_services"`
	WorstServiceHardState             int             `json:"worst_service_hard_state"`
	WorstServiceState                 int             `json:"worst_service_state"`
	StateText                         string          `json:"state_text"`
	ChecksDisabled                    bool            `json:"checks_disabled"`
	FirstGroup                        string          `json:"first_group"`
	Duration                          int             `json:"duration"`
	CommentsCount                     int             `json:"comments_count"`
	StateTypeText                     string          `json:"state_type_text"`
	CheckTypeStr                      string          `json:"check_type_str"`
	CustomCommands                    []interface{}   `json:"custom_commands"`
	ConfigAllowed                     bool            `json:"config_allowed"`
	SourceNode                        string          `json:"source_node"`
	SourceType                        string          `json:"source_type"`
	PerfData                          struct {
		Pkt struct {
			Value int    `json:"value"`
			Warn  string `json:"warn"`
			Crit  string `json:"crit"`
			Min   int    `json:"min"`
			Max   int    `json:"max"`
		} `json:"pkt"`
		Rta struct {
			Value int    `json:"value"`
			Warn  string `json:"warn"`
			Crit  string `json:"crit"`
		} `json:"rta"`
		Pl struct {
			Value int    `json:"value"`
			Unit  string `json:"unit"`
			Warn  string `json:"warn"`
			Crit  string `json:"crit"`
			Min   int    `json:"min"`
			Max   int    `json:"max"`
		} `json:"pl"`
	} `json:"perf_data"`
	UnacknowledgedProblem bool          `json:"unacknowledged_problem"`
	AcknowledgedProblem   bool          `json:"acknowledged_problem"`
	ConfigURL             string        `json:"config_url"`
	PublicCustomVariables []interface{} `json:"public_custom_variables"`
}


